### ISSUE TITLE
Metadata Update

### ISSUE THREAD

**Issue by reeshmabijosh** [cghr-toronto/covid-data#12]
Hello,
Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse as a piece of common COVID-19 data https://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/KONNZO
Would you be willing to help with the maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for the medical science community.

**Comment by rrwen** [comment]
Hi @reeshmabijosh 

CoronaWhy looks like a very interesting project - I would be happy to help with the maintenance of CGHR's open data - though there might be some learning curve as I have not used Dataverse before

**Comment by reeshmabijosh** [comment]
Hello Richard,

Thanks for your willingness to contribute.
 Please register in CoronaWhy Dataverse https://datasets.coronawhy.org/ and
you will get the necessary permissions for editing your dataset.
Then please add relevant metadata - description and keywords to your
dataset.
This is an example of a dataset with good metadata
https://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/TZMOTL


Thanks
Reeshma K

**Comment by rrwen** [comment]
@reeshmabijosh Ok I just registered 👍

**Comment by rrwen** [comment]
@reeshmabijosh I registered at `datasets.coronawhy`:

:link: https://datasets.coronawhy.org/ 

but have yet to receive the permissions for editing `CGHR's open data`:

🔗 https://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/KONNZO

**Comment by rrwen** [comment]
No response - closed
