### ISSUE TITLE
Separate data dictionaries and folders

### ISSUE THREAD

**Issue by rrwen** [cghr-toronto/covid-data#4]
@prod31 We should create a folder for each data file inside a `data` folder, then include any data dictionaries relevant to that file in it (and perhaps other formats if needed).

For example:

```
data
   | --- ined_age_sex_covid19_deaths (folder)
            | --- ined_age_sex_covid19_deaths.csv
            | --- ined_age_sex_covid19_deaths_dictionary.csv
```

The `dictionary.csv` file at the root will describe each data file in this repository.

We can then update this `dictionary.csv` as needed when new data arrives, or each individual `NAME_dictionary.csv` that might be managed by someone else.

**Comment by prod31** [comment]
Ok. Sounds good.
